export default {
  OPEN_MOVIE_PAGE: `OPEN_MOVIE_PAGE`,
  CHANGE_ACTIVE_GENRE: `CHANGE_ACTIVE_GENRE`,
  FILTER_MOVIE_LIST: `FILTER_MOVIE_LIST`,
  CHANGE_NUMBER_MOVIES: `CHANGE_NUMBER_MOVIES`,
  CHANGE_NUMBER_MOVIES_IN_LIST: `CHANGE_NUMBER_MOVIES_IN_LIST`,
  RESET_NUMBER_MOVIES_IN_LIST: `RESET_NUMBER_MOVIES_IN_LIST`,
  SWITCH_MORE_BTN_VISIBILITY: `SWITCH_MORE_BTN_VISIBILITY`,
};
