export default {
  OPEN_MOVIE_PAGE: `OPEN_MOVIE_PAGE`,
  FILTER_MOVIE_LIST: `FILTER_MOVIE_LIST`,
  CHANGE_NUMBER_MOVIES: `CHANGE_NUMBER_MOVIES`,
  CHANGE_NUMBER_MOVIES_IN_LIST: `CHANGE_NUMBER_MOVIES_IN_LIST`,
  RESET_NUMBER_MOVIES_IN_LIST: `RESET_NUMBER_MOVIES_IN_LIST`,
};
